/**
 * Created by zzqno on 2017-2-22.
 * Thread异常处理
 * run()不允许throw exception 所有的异常必须在run方法内进行处理。
 * 线程的的异常 无论是 checked exception or unchecked exception 都必须在run()方法内进行
 * try catch 进行处理
 */
package thread.exception;